name: CI
on:
  repository_dispatch:
    types: [test]
  workflow_dispatch:
    inputs:
      facilitySlug:
        description: "Facility slug"
        required: true
      extraArgs:
        description: "Extra flags passed to script"
        required: false
      skipIssueCreation:
        description: "Skip creating an associated Jira Issue"
        required: false
        default: "true"

env:
  FACILITY_SLUG: ${{ github.event.inputs.facilitySlug || github.event.client_payload.facilitySlug }}
  EXTRA_ARGS: ${{ github.event.inputs.extraArgs || github.event.client_payload.extraArgs }}
  SKIP_ISSUE_CREATION: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.skipIssueCreation == 'true' }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-create-issue:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Test
      run: "echo $SKIP_ISSUE_CREATION"
    - name: Login
      if: "!${{ env.SKIP_ISSUE_CREATION }}"
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: https://ndustrialio.atlassian.net
        JIRA_USER_EMAIL: michael@ndustrial.io
        JIRA_API_TOKEN: cfPeHCNKcOHUHNb22AZU7438
    - name: Create
      id: create
      if: "!${{ env.SKIP_ISSUE_CREATION }}"
      uses: atlassian/gajira-create@master
      with:
        project: NBD
        issuetype: Task
        summary: |
          EKAE: Update Config
        description: |
          This is a automated request to update EKAE config.
        fields: '{"customfield_11300": "15", "customfield_10005": 1.0, "labels": ["ready-to-groom"], "priority": { "id": "2"}}'
    - name: Transition issue
      if: "!${{ env.SKIP_ISSUE_CREATION }}"
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.create.outputs.issue }}
        transitionId: "101"  
    - name: Log created issue
      if: "!${{ env.SKIP_ISSUE_CREATION }}"
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
