name: CI
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-create-issue:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: https://ndustrialio.atlassian.net
        JIRA_USER_EMAIL: michael@ndustrial.io
        JIRA_API_TOKEN: cfPeHCNKcOHUHNb22AZU7438
    - name: Create
      id: create
      uses: atlassian/gajira-create@master
      with:
        project: NBD
        issuetype: Task
        summary: |
          EKAE: Update Config
        description: |
          This is a automated request to update EKAE config.
        fields: '{"customfield_11300": "15", "customfield_10005": 1.0, "labels": ["ready-to-groom"], "priority": { "id": "2"}, "reporter": "c795ce72a4c4463b68ca110"}'
    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.create.outputs.issue }}
        transitionId: "10201"  
    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
